# --- !Ups

create table "COUNTRIES" ("NAME" VARCHAR NOT NULL,"ID" INTEGER NOT NULL PRIMARY KEY);

create table "REGIONS" ("NAME" VARCHAR NOT NULL,"ID_COUNTRY" INTEGER NOT NULL,"ID" INTEGER NOT NULL PRIMARY KEY);

create table "PROVINCES" ("NAME" VARCHAR NOT NULL,"ID_REGION" INTEGER NOT NULL,"ID" INTEGER NOT NULL PRIMARY KEY);

create table "MUNICIPALITIES" ("NAME" VARCHAR NOT NULL,"AREACODE" INTEGER NOT NULL,"ID_PROVINCE" INTEGER NOT NULL,"ID" INTEGER NOT NULL PRIMARY KEY);

create table "CONTACTINFOS" ("NAME" VARCHAR NOT NULL,"ID_COMPANY" INTEGER NOT NULL,"ID" INTEGER NOT NULL PRIMARY KEY);

create table "VATS" ("NAME" VARCHAR NOT NULL,"VALUE" DOUBLE PRECISION NOT NULL,"ID" INTEGER NOT NULL PRIMARY KEY);

create table "BUSINESSTYPES" ("NAME" VARCHAR NOT NULL,"ID" INTEGER NOT NULL PRIMARY KEY);

alter table "REGIONS" add constraint "FK_COUNTRIES_REGIONS" foreign key("ID_COUNTRY") references "COUNTRIES"("ID") on update CASCADE on delete RESTRICT;

alter table "PROVINCES" add constraint "FK_REGIONS_PROVINCES" foreign key("ID_REGION") references "REGIONS"("ID") on update CASCADE on delete RESTRICT;

alter table "MUNICIPALITIES" add constraint "FK_PROVINCES_MUNICIPALITIES" foreign key("ID_PROVINCE") references "PROVINCES"("ID") on update CASCADE on delete RESTRICT;



# --- !Downs

drop table "BUSINESSTYPES";
drop table "VATS";
drop table "CONTACTINFOS";
drop table "MUNICIPALITIES";
drop table "PROVINCES";
drop table "REGIONS";
drop table "COUNTRIES";

